DagMarket/Models/ErrorViewModel.cs
namespace DagMarket.Models
{
    public class ErrorViewModel
    {
        public string? RequestId { get; set; }

        public bool ShowRequestId => !string.IsNullOrEmpty(RequestId);
    }
}

DagMarket/Controllers/AboutUsController.cs
using Microsoft.AspNetCore.Mvc;

namespace DagMarket.Controllers
{
    public class AboutUsController : Controller
    {
        public IActionResult Index()
        {
            return View();
        }
    }
}

DagMarket/Controllers/CategoryController.cs
using Microsoft.AspNetCore.Mvc;

namespace DagMarket.Controllers
{
    public class CategoryController : Controller
    {
        public IActionResult Index()
        {
            return View();
        }
    }
}

DagMarket/Controllers/HomeController.cs
using DagMarket.Models;
using Microsoft.AspNetCore.Mvc;
using System.Diagnostics;

namespace DagMarket.Controllers
{
    public class HomeController : Controller
    {
        private readonly ILogger<HomeController> _logger;

        public HomeController(ILogger<HomeController> logger)
        {
            _logger = logger;
        }

        public IActionResult Index()
        {
            return View();
        }

        [ResponseCache(Duration = 0, Location = ResponseCacheLocation.None, NoStore = true)]
        public IActionResult Error()
        {
            return View(new ErrorViewModel { RequestId = Activity.Current?.Id ?? HttpContext.TraceIdentifier });
        }
    }
}

DagMarket/Views/AboutUs/Index.cshtml
@{
    ViewData["Title"] = "О нас";
}

   
<section id="aboutUs"  class="d-flex align-items-center justify-content-center">
    <div class="container">
        <div class="row justify-content-center">
            <div class="aboutUs-card col-lg-6 col-md-12">
                <img src="~/image/iam.svg" alt="I'am" width="300" height="300" />
                <h2 class="text-center">Я Даниял Идрисов</h2>
            </div>

            <div class="aboutUs-text col-lg-6 col-md-12 d-flex align-items-center">
                <p class="text-center ">Задача организации, в особенности же реализация намеченного плана развития позволяет выполнить важнейшие задания по разработке форм воздействия. Практический опыт показывает, что постоянное информационно-техническое обеспечение нашей деятельности влечет за собой процесс внедрения и модернизации системы масштабного изменения ряда параметров. Значимость этих проблем настолько очевидна, что консультация с профессионалами из IT в значительной степени обуславливает создание существующих финансовых и административных условий.</p>
            </div>
        </div>
    </div>
</section>

DagMarket/Views/Category/Index.cshtml
@{
    ViewData["Title"] = "Категории";
}

   
<section id="category"  class="d-flex align-items-center justify-content-center"> 
    <div class="container">
         <div class="row justify-content-center">
          <h2 class="text-center">
            Категории товаров
          </h2>
        </div>
        <div class="row justify-content-center">
            <div class="col-xl-3 col-lg-4 col-md-6 wrap_images">
                <a asp-area="" asp-controller="Home" asp-action="Index"> 
                <div class="card" style="width: 18rem;">
                <img src="~/image/vegetablesandfruits.svg" class="card-img-top" alt="..." width="300" height="300">
                  <div class="card-body">
                    <p class="card-text">Овощи и фрукты</p>
                  </div>
                </div>
                </a>
            </div>

             <div class="col-xl-3 col-lg-4 col-md-6">
                <a asp-area="" asp-controller="Home" asp-action="Index"> 
                <div class="card" style="width: 18rem;">
                <img src="~/image/meat.svg" class="card-img-top" alt="..." width="300" height="300">
                  <div class="card-body">
                    <p class="card-text">Мясо</p>
                  </div>
                </div>
                </a>
            </div>

             <div class="col-xl-3 col-lg-4 col-md-6">
                <a asp-area="" asp-controller="Home" asp-action="Index"> 
                <div class="card" style="width: 18rem;">
                <img src="~/image/seafood.svg" class="card-img-top" alt="..." width="300" height="300">
                  <div class="card-body">
                    <p class="card-text">Морепродукты</p>
                  </div>
                </div>
                </a>
            </div>

             <div class="col-xl-3 col-lg-4 col-md-6">
                <a asp-area="" asp-controller="Home" asp-action="Index"> 
                <div class="card" style="width: 18rem;">
                <img src="~/image/dairy.svg" class="card-img-top" alt="..." width="300" height="300">
                  <div class="card-body">
                    <p class="card-text">Молочная продукция</p>
                  </div>
                </div>
                </a>
            </div>

            <div class="col-xl-3 col-lg-4 col-md-6">
                <a asp-area="" asp-controller="Home" asp-action="Index"> 
                <div class="card" style="width: 18rem;">
                <img src="~/image/beverages.svg" class="card-img-top" alt="..." width="300" height="300">
                  <div class="card-body">
                    <p class="card-text">Напитки</p>
                  </div>
                </div>
                </a>
            </div>


             <div class="col-xl-3 col-lg-4 col-md-6">
                <a asp-area="" asp-controller="Home" asp-action="Index"> 
                <div class="card" style="width: 18rem;">
                <img src="~/image/tea.svg" class="card-img-top" alt="..." width="300" height="300">
                  <div class="card-body">
                    <p class="card-text">Чай</p>
                  </div>
                </div>
                </a>
            </div>

             <div class="col-xl-3 col-lg-4 col-md-6">
                <a asp-area="" asp-controller="Home" asp-action="Index"> 
                <div class="card" style="width: 18rem;">
                <img src="~/image/coffe.svg" class="card-img-top" alt="..." width="300" height="300">
                  <div class="card-body">
                    <p class="card-text">Кофе</p>
                  </div>
                </div>
                </a>
            </div>

             <div class="col-xl-3 col-lg-4 col-md-6">
                <a asp-area="" asp-controller="Home" asp-action="Index"> 
                <div class="card" style="width: 18rem; ">
                <img src="~/image/sweets.svg" class="card-img-top" alt="..." width="300" height="300">
                  <div class="card-body">
                    <p class="card-text">Сладости</p>
                  </div>
                </div>
                </a>
            </div>
        </div>
    </div>
</section>

DagMarket/Views/Home/Index.cshtml
@{
    ViewData["Title"] = "Главная";
}

   



    <section id="main-screen" class="d-flex align-items-center justify-content-center">
      <div class="container">
        <div class="row justify-content-center">
          <div class="col-xxl-12 col-lg-12 col-sm-12">
            <h1>DагМаркет</h1>
            <p>Здесь вы найдете все что искали</p>
          </div>
        </div>

        <div class="row justify-content-center">
          <div class="col-xxl-12 col-lg-8 text-center">
          <form class="d-flex">
            <input class="form-control me-2" type="search" placeholder="Поиск" aria-label="Search">
            <button class="btn btn-success" type="submit">Поиск</button>
          </form>
        </div>
        </div>
        
      </div>
    </section>

    <section id="main-category" class="d-flex align-items-center justify-content-center">
      <div class="container">
        <div class="row justify-content-center">
          <div class="about-category col-xl-6 col-md-12 order-2 order-lg-1 ">
            <h2>О DагМаркет</h2>
            <p>На сайте DагМаркет публикуется товары, а именно продукты питания, от крупных магазинов или поставщиков.<br/> Каждый человек может найти нужный ему товар на нашем сайте. Для этого потребуется ввести в поисковой строке наименование товара. Или перейти в категории и там по категориям найти необходимый товар.</p>
            <a href="#" class="btn btn-outline-success">Категории</a>
          </div>
          <div class="img-category  col-xl-6 col-md-12 order-1 order-lg-2 " >
            <a asp-area="" asp-controller="Home" asp-action="Index"><img src="~/image/slide2.jpg" alt=""  class="img-fluid"></a>
          </div>
        </div>
      </div>
    </section>

    <section id="best-product" class="d-flex align-items-center justify-content-center">
      <div class="container">
        <div class="row justify-content-center">
          <h2 class="text-center">
            Наиболее просматримаемые продукты
          </h2>
        </div>
        <div class="row justify-content-center">
          <div class="col-xl-3 col-md-6 col-sm-12 jus">
            <div class="card" style="width: 18rem;">
              <img src="~/image/slide1.jpg" class="card-img-top" alt="...">
              <div class="card-body">
                <h5 class="card-title">Название карточки</h5>
                <p class="card-text">Some quick example text to build on the card title and make up the bulk of the card's content.</p>
                <a asp-area="" asp-controller="Home" asp-action="Index" class="btn btn-primary">Go somewhere</a>
              </div>
            </div>  
          </div>

          <div class="col-xl-3 col-md-6 col-sm-12">
            <div class="card" style="width: 18rem;">
              <img src="~/image/slide1.jpg" class="card-img-top" alt="...">
              <div class="card-body">
                <h5 class="card-title">Название карточки</h5>
                <p class="card-text">Some quick example text to build on the card title and make up the bulk of the card's content.</p>
                <a asp-area="" asp-controller="Home" asp-action="Index" class="btn btn-primary">Go somewhere</a>
              </div>
            </div>  
          </div>

          <div class="col-xl-3 col-md-6 col-sm-12">
            <div class="card" style="width: 18rem;">
              <img src="~/image/slide1.jpg" class="card-img-top" alt="...">
              <div class="card-body">
                <h5 class="card-title">Название карточки</h5>
                <p class="card-text">Some quick example text to build on the card title and make up the bulk of the card's content.</p>
                <a asp-area="" asp-controller="Home" asp-action="Index" class="btn btn-primary">Go somewhere</a>
              </div>
            </div>  
          </div>

          <div class="col-xl-3 col-md-6 col-sm-12">
            <div class="card" style="width: 18rem;">
              <img src="~/image/slide1.jpg" class="card-img-top" alt="...">
              <div class="card-body">
                <h5 class="card-title">Название карточки</h5>
                <p class="card-text">Some quick example text to build on the card title and make up the bulk of the card's content.</p>
                <a asp-area="" asp-controller="Home" asp-action="Index" class="btn btn-primary">Go somewhere</a>
              </div>
            </div>
          </div>

        </div>
      </div>
    </section>
    
  

DagMarket/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>@ViewData["Title"] - DagMarket</title>
    <link
      href="https://cdn.jsdelivr.net/npm/bootstrap@5.2.0-beta1/dist/css/bootstrap.min.css"
      rel="stylesheet"
      integrity="sha384-0evHe/X+R7YkIZDRvuzKMRqM+OrBnVFBL6DOitfPri4tjfHxaWutUpFmBp4vmVor"
      crossorigin="anonymous"
    />
    <link rel="stylesheet" href="~/css/style.css" asp-append-version="true" />
</head>
<body>
  
    <header>
        <nav class="navbar navbar-expand-xl navbar-light bg-light">
            
          <div class="container">
              
            <a asp-area="" asp-controller="Home" asp-action="Index" class="navbar-brand col-4"
              ><img src="~/image/logo.png" alt="logo" width="173" 
            /></a>
            <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
                <span class="navbar-toggler-icon"></span>
              </button>
            
            <div class="collapse navbar-collapse" id="navbarSupportedContent">
              <ul class="navbar-nav col-8">
                <li class="nav-item">
                  <a class="nav-link active" aria-current="page"  asp-area="" asp-controller="Home" asp-action="Index">Главная</a>
                  
                </li>
                <li class="nav-item">
                  <a class="nav-link" asp-area="" asp-controller="Category" asp-action="Index">Категории</a>
                </li>
                    
                <li class="nav-item">
                  <a class="nav-link"  asp-area="" asp-controller="AboutUs" asp-action="Index">О нас</a>
                </li>
                <li class="nav-item">
                  <a class="nav-link"  asp-area="" asp-controller="Home" asp-action="Index">Контакты</a>
                </li>
            </ul>
            
                <ul class="navbar-nav col-4">
                 
                
                <li class="nav-item">
                  <a class="nav-link"  asp-area="" asp-controller="Home" asp-action="Index">Вход</a>
                </li>
                <li class="nav-item">
                  <a class="nav-link"  asp-area="" asp-controller="Home" asp-action="Index">Регистрация</a>
                </li>
              </ul>
            </div>
          </div>
        </nav>
    </header>

        <main role="main" class="pb-3">
            @RenderBody()
        </main>

  
    <footer class="py-3 my-4">
      <div class="container">
          <ul class="nav justify-content-center border-bottom pb-3 mb-3">
            <li class="nav-item"><a asp-area="" asp-controller="Home" asp-action="Index" class="nav-link px-2 text-muted">Главная</a></li>
            <li class="nav-item"><a asp-area="" asp-controller="Home" asp-action="Index" class="nav-link px-2 text-muted">Категории</a></li>
            <li class="nav-item"><a asp-area="" asp-controller="Home" asp-action="Index" class="nav-link px-2 text-muted">О нас</a></li>
            <li class="nav-item"><a asp-area="" asp-controller="Home" asp-action="Index" class="nav-link px-2 text-muted">Контакты</a></li>
          </ul>
          <p class="text-center text-muted">© 2022 DагМаркет</p>
      </div>
    </footer>
   
    <script
      src="https://cdn.jsdelivr.net/npm/bootstrap@5.2.0-beta1/dist/js/bootstrap.min.js"
      integrity="sha384-kjU+l4N0Yf4ZOJErLsIcvOU2qSb74wXpOhqTvwVx3OElZRweTnQ6d31fXEoRD1Jy"
      crossorigin="anonymous"
    ></script>
    @await RenderSectionAsync("Scripts", required: false)
</body>
</html>